### ISSUE TITLE
cutout schematic on website

### ISSUE THREAD

**Issue by adampbeardsley** [astrochart/astrochart.github.io#3]
The lower edge on the right two panels should be 12.3cm (not 24cm)

![image](https://user-images.githubusercontent.com/4752917/74880839-5e5ae080-5329-11ea-8205-9bd2b7c034e3.png)

**Comment by lmberkhout** [comment]
@adampbeardsley also update the measurements with a height

**Comment by adampbeardsley** [comment]
@lmberkhout this is done, right? Done with PR #12 
https://astrochart.github.io/website/hardware.html#build
