### ISSUE TITLE
Where's my tabs

### ISSUE THREAD

**Issue by lmberkhout** [astrochart/astrochart.github.io#37]
<img width="1440" alt="Screen Shot 2022-10-12 at 12 56 03 PM" src="https://user-images.githubusercontent.com/34925577/195435719-b66b6aa8-7060-4cda-b46b-fafb31259123.png">
No tabs on chrome on a 2020 macbook pro

**Comment by lmberkhout** [comment]
<img width="1440" alt="Screen Shot 2022-10-12 at 12 57 12 PM" src="https://user-images.githubusercontent.com/34925577/195435872-cc75ef10-ff58-45f6-ad2d-1f58a45176dc.png">
If you fumble around in the dark you can find them but they should be visible

**Comment by adampbeardsley** [comment]
Ah, this is a window size issue. The template tries to dynamically change the view with the size of the window, and I think we didn't develop this size. I don't have a solution, other than to make the window bigger. But we should get the next student to fix this.
